name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
         
          start: npm run cypress-regression-pack
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
              name: cypress-screenshots
              path: cypress/screenshots
